apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: actual-secrets
    namespace: actual
spec:
    secretTemplates:
        - name: actual-secrets
          stringData:
            ACTUAL_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:clwUlU67v1bz0+XSd3iT2LPgmZPXzALtl8DQik1PG9Mn8j/wscCEgg==,iv:q6zDIY5TF1jrXDxdJugyaxxD3/i5h2dtpvX4EbKeKqc=,tag:OK/51yQc6WLMY2vGJdfUbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYTFkNHB1R1hqejNZMXlI
            MC96c3V0NFJXYUViMm1OQ1BEa25BNFVUZjNNCmZPUFVUQUIxZHE2QU4wblhIMU9G
            SXlSMFE4OWxwdXNESWlBd25HcnVtSzAKLS0tIGVRSldGWmtIZlRiaWh0YjgzUFNT
            NG9GNWdwS2tGN3lJbDFuc1haUEptQ1kK6xeyDrELR5RUys67w5yM8CpXq6eS2Jzc
            0k92dXfHCXwDLNifvvI3YTOe1ChT2t1tiCmyJbShXjNAL8j1O773FA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u7wzh5ljlvz2kq7ha7pxpky2rw5llzgnhkaj0xq80httdpxvsagqz8pzll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T18:22:16Z"
    mac: ENC[AES256_GCM,data:k3OVe1uw+N5IhxXaBVVqchHbQ4ettxSkOZ0bK/J8EDZtbTtB4hrs6epND3rBq4KmdtwhJ/xff7WJB8nfwLWBSjb/r1R5BmBFB5IBk/t+oPisZNkWhdzbragclEatbt5KfTsjw4ZEMor0ZiKHRamK/xXTdK2m5/2KLIxMmOYAYHU=,iv:FBxWkTwpcHGuRos6PO7wsXWoKxBVk2LlTQ4AL4FEeVM=,tag:kmJmVIb7Z0CAGt2my4A/vg==,type:str]
    version: 3.13.2
