apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: actual-oidc-authentik-secret
    namespace: authentik
spec:
    secretTemplates:
        - name: actual-oidc-authentik-secret
          stringData:
            OIDC_ACTUAL_CLIENT_SECRET: ENC[AES256_GCM,data:tDiFMzV+vPzrNwORHZqIvmWZFmTCu184E8Sd+vtAh7Xzg7cce9dPVQ==,iv:5ikygi1sMIg0DJYQjVCqNBuDtop+6ZyKygbtEhWFnzk=,tag:Vinnd51MI/ILwJqlxahEjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvV0RKYmNOWmxUelg3TU5l
            bEFGbDVnekZ1UW44UjBIcEdxT1FMQkl1UFg4ClNibTVxWE4vVEo2T2NjYTdhTUZZ
            YWRLYW15TTk4c1J5K0k3N1g1ZGFPN0kKLS0tIFlNRSt3V1VJZ2Q4QnQ3OVkvNzJi
            Z0xTbnk1RmVML0VVb3ZlbzErQXIwVTAKjOm6mU1GMpRHZpl23f6f7Z4aM26fM7Xc
            +ThAGpPVbUkjfPbSfIV5UCZ4yDfnAA9Vldm1jdFk+luQOjJ/FyWxSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u7wzh5ljlvz2kq7ha7pxpky2rw5llzgnhkaj0xq80httdpxvsagqz8pzll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T18:22:16Z"
    mac: ENC[AES256_GCM,data:wFWCw2yJCd4KWlzJyLI6ZG0s3ftcXKlgjsOWM3etMAi8IB9VwovulPLIo92DMWyvRqXN9iM1Ii6Wx91tt47HoEF/KNRSSX4VwMXubKNVSYyU/y3Hr4qhwG432Juz89Fw46XeA6GquvQT42FXXnogeuEYu9VbjENXT3cVhcyoGuU=,iv:AgCJjlmlQiAgtxjIGxsvu6BdNOFptYrj8jd5NRbHAnM=,tag:xf1rQv9pkqCFBHUNIoX61w==,type:str]
    version: 3.13.2
