apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-oidc-secrets
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-oidc-secrets
          stringData:
            OIDC_ARGOCD_CLIENT_SECRET: ENC[AES256_GCM,data:is1sAAAq14wdA8sVR4qgMQOnz8CGHWXRcUY1aGdi6diPeSF9+BXsQYa1DmM9QNDFXwckcJRTYr6tnkr3uobX7A==,iv:guRwYirpsw2mgnd8bYgK81Hu07i7oM7zGdlUGkXFJH8=,tag:ooByT/D2BOU7lUHF22IDZA==,type:str]
            OIDC_BACKSTAGE_CLIENT_SECRET: ENC[AES256_GCM,data:ZkusLniRTWh1R6G9KH8exbW0JMDGhNRtbHyAtpoITnBMOlq4JKRgPdHMordouSEFhQY+D/5gd9zkwhiiOOaZSg==,iv:GV66h0pI94OfF9ew5LmN10kEPNgBOtZRPfrfUyOG0OU=,tag:2JZzpUAHTt8tNntGSO3koQ==,type:str]
            OIDC_DAGSTER_CLIENT_SECRET: ENC[AES256_GCM,data:gl7nS49S5XExG1WhlFTq2kE1Dw5X0zHOlWB/O7/u/TUfp7k7G1cuuqNFA/do1nRsGs7XWLyzl7s7Trj7f98+wEGfkjqrOY6H75aVXnEkf1L6rRKsMZG9yG66E/2kywHOZTX0nQbea8HqFjTWXYN9hOR1tWPSXoii/VVfKcuQ+EE=,iv:ZPgSCjOES8MMUuZGGyj6bJ2aZru3HbPFc39dJlTo+SE=,tag:VEIx9AP1LhjEVSZdPG5dfw==,type:str]
            OIDC_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:slhWsYIlY3MRj1v5mvdqyciAiTwRtEZZjuH6AuEwc5aQnV9I0RNZl8obyTfyqq3Dk+zEj2jNJvo9rdjVGuVn3lTtksZn6pJvbcmPlCmoySSZPCkw+UevwhPsPGBziL8EfCSZsIEj6cuN9kmpobL6FbTXnxfpdUoJUrsSdwyq0s0=,iv:oy6tuCJpPfqRoreIFg4dGF2XK+TuZ05+weGEkYL1abU=,tag:4mutzXf9lIvXfsp4u6VP9g==,type:str]
            OIDC_HARBOR_CLIENT_SECRET: ENC[AES256_GCM,data:PtjzegQoKyEV91JuSWQ1uaSe+pR605KP/Z8y1PYst6f/FJ1EkCiZhYxVHOmZf3wLV8PFdQTWkK5XouV8t873AqH5xmsy/1dxsamWQEhBc1EeVdqewocgUYfGrtrReYRVBvyNPwwgB7p7oO8GnsHYx0aV98tnEfgkpznbaTyTiyg=,iv:knhlPiyNDhd9wSKsSzWoC8qj4wMgD5B7yKQvvjJdNpA=,tag:1/7nlwCTNvW8lOBr/xoIbA==,type:str]
            OIDC_MINIO_CLIENT_SECRET: ENC[AES256_GCM,data:flytZ93YNFiNy0PZ/39njTKkPD+aJnDtqCXgfy5POSeMjeLH4dC/gUtUsUC0PhUxxZs8j+iMMwvHSIFX2TNOdx3HrNUZmcpatv52MbYK//LAJQGCN2va/W8D1x3+eVXVPadK2IQOAEWH1ZndtH2N8LljN1lUBypu6qQQc85GrZI=,iv:p4/kHnuQ9+n58USB+ly8pZfkhfC1DeitYC4LTWubjqU=,tag:LCh+S+ZqLXYzpp95/Q9rUg==,type:str]
            OIDC_JOHANJOEL_CLIENT_SECRET: ENC[AES256_GCM,data:q3TMzINbiJ5ASbwEtfLsq//1XzplA/tweO5dLTaz3Ey151cZ3Oj/w3ilAcuFmlbA1Pg/CLpVXoQnKegKCdW6+rZ7i2EmJ4yBvHZnu5+h0yHMglz86lfE7hejGWyXcn4v7Yk0UoW1saY4fJPRxBNWavYt1PWwF8a6JRKbb7R7QRw=,iv:7/3Co6TolEb8vH9DmBnRpGSGe5yJ2qLQzwcP3IGT4gk=,tag:rWNNcQzrwhHksj6RnwuSmw==,type:str]
            OIDC_MAILPIT_CLIENT_SECRET: ENC[AES256_GCM,data:0DN0D3PTtHpkG5nXDIpoGh0LP2djuWBwfqjbmoS99nEta6BcqUg5O4ZjauzWubhfNuESS6OYvCKoLsQLAMf2X126gbLXlcADPhxCpa2bT6eEtkq3X+9Cp4JU/uo0OVJk4kbiiU8ifNftzAq/z+wPorC07qIhpA7O/fVKsFoZzG4=,iv:OaFLG7wf8mpfnzFbmN8R/81ni2kKW0I9slUeTDAoU0A=,tag:8YkhuGZPyY+qphBXiB4nPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S0RkM0d1UzFhVDBEbFJl
            Y1dkOVJRMXR4TlR4YlJueXlHSmJXSHdsNDNjCnExR3FLNnI4MDR5QTZNczUyVHhk
            SUE5dVVPQU5EQTdubDBuOUt2TTBldG8KLS0tIGRHb2tSZXhxclNTZHd1U1dqWml5
            UlBGMzVHYU1qb3VXZE9BVk9tL01KY2sK8u9kG9e/ct3Ym6i0wUZYhZWdkEkoCDhU
            MSAi8L5b5KVoZ4D7ag86Fb0TuzRgC1Y+M7409j/VuKU2D7un+G2M+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u7wzh5ljlvz2kq7ha7pxpky2rw5llzgnhkaj0xq80httdpxvsagqz8pzll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T12:30:47Z"
    mac: ENC[AES256_GCM,data:Bekop2Yb4B2egWIxhCIjfY8u58dgPenInVEtDohJz88NE7Au5eBpjUQ7c8ZrxKa5uFfGs3iaBxc77mXZHZsNsRsqvAqphRnr5QNOHNltnMVbDtKAlK/mYWpA9paOg3U21yw8yKJCx4nYV0pSASrsk09BeqfeOFRK2PWfRxgO1E8=,iv:IykrrmuH8vCG+eTXs9l/4dIf87xAljYM+un3z/KSdNk=,tag:Cl6Vytkb4BKxxl4TSaH0qA==,type:str]
    version: 3.13.1
