apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-oidc-secrets
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-oidc-secrets
          stringData:
            OIDC_ARGOCD_CLIENT_SECRET: ENC[AES256_GCM,data:is1sAAAq14wdA8sVR4qgMQOnz8CGHWXRcUY1aGdi6diPeSF9+BXsQYa1DmM9QNDFXwckcJRTYr6tnkr3uobX7A==,iv:guRwYirpsw2mgnd8bYgK81Hu07i7oM7zGdlUGkXFJH8=,tag:ooByT/D2BOU7lUHF22IDZA==,type:str]
            OIDC_BACKSTAGE_CLIENT_SECRET: ENC[AES256_GCM,data:ZkusLniRTWh1R6G9KH8exbW0JMDGhNRtbHyAtpoITnBMOlq4JKRgPdHMordouSEFhQY+D/5gd9zkwhiiOOaZSg==,iv:GV66h0pI94OfF9ew5LmN10kEPNgBOtZRPfrfUyOG0OU=,tag:2JZzpUAHTt8tNntGSO3koQ==,type:str]
            OIDC_DAGSTER_CLIENT_SECRET: ENC[AES256_GCM,data:gl7nS49S5XExG1WhlFTq2kE1Dw5X0zHOlWB/O7/u/TUfp7k7G1cuuqNFA/do1nRsGs7XWLyzl7s7Trj7f98+wEGfkjqrOY6H75aVXnEkf1L6rRKsMZG9yG66E/2kywHOZTX0nQbea8HqFjTWXYN9hOR1tWPSXoii/VVfKcuQ+EE=,iv:ZPgSCjOES8MMUuZGGyj6bJ2aZru3HbPFc39dJlTo+SE=,tag:VEIx9AP1LhjEVSZdPG5dfw==,type:str]
            OIDC_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:slhWsYIlY3MRj1v5mvdqyciAiTwRtEZZjuH6AuEwc5aQnV9I0RNZl8obyTfyqq3Dk+zEj2jNJvo9rdjVGuVn3lTtksZn6pJvbcmPlCmoySSZPCkw+UevwhPsPGBziL8EfCSZsIEj6cuN9kmpobL6FbTXnxfpdUoJUrsSdwyq0s0=,iv:oy6tuCJpPfqRoreIFg4dGF2XK+TuZ05+weGEkYL1abU=,tag:4mutzXf9lIvXfsp4u6VP9g==,type:str]
            OIDC_MINIO_CLIENT_SECRET: ENC[AES256_GCM,data:flytZ93YNFiNy0PZ/39njTKkPD+aJnDtqCXgfy5POSeMjeLH4dC/gUtUsUC0PhUxxZs8j+iMMwvHSIFX2TNOdx3HrNUZmcpatv52MbYK//LAJQGCN2va/W8D1x3+eVXVPadK2IQOAEWH1ZndtH2N8LljN1lUBypu6qQQc85GrZI=,iv:p4/kHnuQ9+n58USB+ly8pZfkhfC1DeitYC4LTWubjqU=,tag:LCh+S+ZqLXYzpp95/Q9rUg==,type:str]
            OIDC_JOHANJOEL_CLIENT_SECRET: ENC[AES256_GCM,data:q3TMzINbiJ5ASbwEtfLsq//1XzplA/tweO5dLTaz3Ey151cZ3Oj/w3ilAcuFmlbA1Pg/CLpVXoQnKegKCdW6+rZ7i2EmJ4yBvHZnu5+h0yHMglz86lfE7hejGWyXcn4v7Yk0UoW1saY4fJPRxBNWavYt1PWwF8a6JRKbb7R7QRw=,iv:7/3Co6TolEb8vH9DmBnRpGSGe5yJ2qLQzwcP3IGT4gk=,tag:rWNNcQzrwhHksj6RnwuSmw==,type:str]
            OIDC_UMAMI_CLIENT_SECRET: ENC[AES256_GCM,data:TPv5DfM7xvnbxcfbFndlTuje0HxZ2pgrcVE3VGqKF+xxWHxvyq/NB5JDZh2YJIT1ZkeEMzEoLkfkI46ZIIOvU6Hqh1rZ23tbk2fa8j3x6QYhD1X97HX0Wv/G49V/HQYCp+sxXEDrry6hVOR1E3nynChBVDHCIi9Pv9+ldBITDEk=,iv:JeiTIBNKoncLGCTsIJFkVlNe8+dSUrnleRKGhaHYQU4=,tag:r8BAPgI0eO/AUYC3+s0Ytg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S0RkM0d1UzFhVDBEbFJl
            Y1dkOVJRMXR4TlR4YlJueXlHSmJXSHdsNDNjCnExR3FLNnI4MDR5QTZNczUyVHhk
            SUE5dVVPQU5EQTdubDBuOUt2TTBldG8KLS0tIGRHb2tSZXhxclNTZHd1U1dqWml5
            UlBGMzVHYU1qb3VXZE9BVk9tL01KY2sK8u9kG9e/ct3Ym6i0wUZYhZWdkEkoCDhU
            MSAi8L5b5KVoZ4D7ag86Fb0TuzRgC1Y+M7409j/VuKU2D7un+G2M+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u7wzh5ljlvz2kq7ha7pxpky2rw5llzgnhkaj0xq80httdpxvsagqz8pzll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T21:13:28Z"
    mac: ENC[AES256_GCM,data:Fh9ypb5xKcb4wGYLOCxfjK2WfhxQ6xTbtj/3vJYDLZ5Mg2mVOfK0pHtdGW9ZgJTFHPoHmXfHK5O4W5JeHj5HeMKGtEmQPZ54zG6DeLMgWFfpJzMKqMarp4Fck4fvkK/BgMnQ3cqkOOiBOCZFHLcaJXUN7+y1d6p47Z41BNadqhU=,iv:7RPKiuX3gQ7OeMDyk6xJuvJ9oXFhur/vgO9PvYREq/g=,tag:5HuYtZ2Pvgj7oxOa8OtH6g==,type:str]
    version: 3.13.1
