apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-oidc
    namespace: monitoring
spec:
    secretTemplates:
        - name: grafana-oidc
          stringData:
            GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:JCNSrRTPmik/7C0Y/KhQki+IsTpsI522x/c0Y0nKfLcAJeY4y9nuXA==,iv:ulsbOyRdkHaJfsMv60n3MiW+hvpsQtmQIF9V7ju7FZc=,tag:prVqT1XIT7st/Yqv6uhUVw==,type:str]
            GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:SrOyg7j/8JSOBgbxbiiCAaBj0iWcGDZpGESa66ZS1kAGvx/35N7xH74xIZ3BNfobSC8YSLrQ9wYNBBQXbgIqvGehZNqLVHsvAPpPcgdlVUkIorSUB5OEqZVGbrYbTvco97ev96kj7YRmxmJWEUAaW0wjMIrIpJa1Oxy1qiFNnHY=,iv:MqIudlS4g9Myxg5EKfp6ga/SOaMfnyJRyTamV6b5LJw=,tag:biXCvArjkt/+Y83YnHgnOg==,type:str]
            GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:cp/kaW2FNMkke/d7aLPgevnV+xH+K5SKE+CLw9DRVyz3yZLMoBfL6SttnAeq0zPL,iv:F2RdBJdlJOunFFzomGECyIevGkpU34ulCskI/bQuJsQ=,tag:hb09TAOg1TaYeBmv/mCHdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUk1qcjlOM0RjbDdQNUVv
            azFlL1A0ajMwbExmQkZXSXFHbXFBNmQ5UjAwCmdsWUYvR0ljNlRZbkFJYzRyTUJ5
            WmQ1RitUa0h6Y0RCR0MyMUIybGZXbG8KLS0tIElVbVB6eDVpaFp5ZXU0M1Z3dUt2
            VzRrbm5hU0JkaUoybzVaV3NjNWRnKzgKo/g5cHTFtOO9sDBVJyF9f1Xm7+MIQ5DO
            +jTSbN0YcBqJXgkpIq1A8c9E8Fjo8xEq5p+PxthaAXCOdNr7v/CKNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u7wzh5ljlvz2kq7ha7pxpky2rw5llzgnhkaj0xq80httdpxvsagqz8pzll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T22:33:23Z"
    mac: ENC[AES256_GCM,data:2Inf/Gc+dMuXG3xWXbpGvX0jJrh6WTMvnECfi/s9HW8KO6p9U9hh+NwUxwMom+fmyu5EglA+HdgqMaxCaAnUC3gIV1UYCyZjVYwa8DM0bzUWyqnSEv9gE/r8fZHRS+Ac5ikg5xAB3J2ZeUM4aSWoxsPufDOj01FOa+w5gonOEkg=,iv:kvcQCKY7vROf0Lrq/pJlqWs+Bw8NYoVgw8KHgEfrfkY=,tag:D7DJKiBy7vLl25Rg06uzIA==,type:str]
    version: 3.13.1
