apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: johanjoel-oauth2-proxy
    namespace: johanjoel
spec:
    secretTemplates:
        - name: johanjoel-oauth2-proxy
          stringData:
            OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:BrO+guMpurXk7u+8c+3nuCm/lF2wwUdyL4qoMJeNZZMHe12eG5ieTw==,iv:es/8R+M2LuKoiiXzYYvsacc23MzBX/DiLFIQZ84XvY0=,tag:6eOZA1NIbsRkFSzK4KDegA==,type:str]
            OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:HBwajQG/kFRw1wAhKuBw5OYf7/StDYXppQVr679BvuRdnVUZR6aJ6gs8wnYLozWxxOO3Grtde2D/r1e9LyZyOcnuOwLycc9ZH+gURjbt309lWFhZx8tTRSsdyh4Ns3YUzttgDTPuf+ae29n6phYiVwleKlKyse1x/uV91I94Lyg=,iv:MNFJ+Mq2Pw6ECAbAaHJDqcLUvsq6EIqlAvdyD88BQ/o=,tag:o0LQZExuk3D0GocSTrxwRQ==,type:str]
            OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:muQIE58zDEMML9bDA6CXhgjbSrIAFIX+yyx/MtAgNMCl75Sq9ySmiJy2mpM=,iv:BRcZzGZWxwOO+ag9qhnuM6fwzUOhq0RmBoxe7PdB3Y4=,tag:N+aQN7+EA/zB2EYNFMZooQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUEN0N0hPMWErNHRHMXpG
            TEdHZ3JJR1pnMjQreVk0TGhqMTBUOFNQT1NVCmlRZTRtaEdXSVRZeW5hSTRtZTQ0
            bHRVbWM3R09nMy9IRlp6d0tmWi9XTm8KLS0tIE0xb2ZDTGMrdndTdHk2QWE5VTgr
            MTR5YzNOdldOamx0S05namNjelVwN2cKRFujr4v/VXh8XQ9VRak29JFrrFGLkxhS
            IKYObHpJIX7ohcmLf1emInuR0QSiNcUIiZiRkE9Q/fBdIdPB9W+o7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u7wzh5ljlvz2kq7ha7pxpky2rw5llzgnhkaj0xq80httdpxvsagqz8pzll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T18:37:20Z"
    mac: ENC[AES256_GCM,data:vZ0iMSmyZ6JwjDcmjRPsEOk+mbT44/CKznZBkfO7elgGm+OqCPC0gfqZ9HagH9dgn/+IdDJBH7d4OwOQ6UvkpGkOOx4ohzMUFDRm0ywmKvRnKrv5cVGO7o/gc+fg53DDNtvLl11369m1WXc8RR16G5LFkrriLzFBBp43gJZ3GOE=,iv:3fuudc10y9O9ysr6YKXIeigxxcJVNSgo+WTEXIUNJfA=,tag:HXcEuXnsMFnUpNbr0xw9Cg==,type:str]
    version: 3.13.1
