apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mailpit-oauth2-proxy
    namespace: mailpit
spec:
    secretTemplates:
        - name: mailpit-oauth2-proxy
          stringData:
            OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:xkm8io/b+31BnlJ3hypG41IEvwDKLDuB0BNSjwj9kba54ZjUU/nM+w==,iv:SdaOdfQMpCQyiuBlgY1GwYv8X+lyJkl3X4xDfjimZOU=,tag:zxWkwzNnNwbgP3JvwbL9XQ==,type:str]
            OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:7uy0vHGhHdmbVvMZyWe8pMyxrCw2JJxC+4d4u2kCVvyLX5uESOGy1Nk8ncrairsGa8JL3IKnUtT/UwMR0olDNgpcEXUxMYKoDEl7zMA6V9POTgrkYfxWg1nH+f4+QRfE4HznWThm1utfOtQLWDmpggjO8qbXlYFJr4TZ48vojDs=,iv:/73IDb6tWGcA1rS3zVO1ivbYUz9W0yiARygDhpLx7pU=,tag:1nIvgWrZqWKvfxM51QyzPA==,type:str]
            OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:mVgLenTAH5GKrhCq1U7cIFnePH3ObpVVPZsbRGHmFLW/5UEkYtb1lK1oIW4=,iv:+/1giogFdOm/uSolqD8xtkoWA6j4lscAVv6YN0uUVYY=,tag:EGB4xkTTKFu9Wgu75HhOVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOFNramQxOVpZZUFVdURH
            c1pWSitpVWpiUk5QdWcvT0FoR3NOb0VZT1hFCmZuQk1VK0JlVlVGWjRzQ0t2VVZp
            OUhCZHRtWWxRWHNyYzhaVk5OUlpZdlUKLS0tIEpnNmZxc2F2TnV1R1cxa3lYVnZw
            UHVJY2dmL0tEcTBLWjU5MG9RUWp1OTAK/DCxRC1cqmdAihdzVTTAI2SyywGoHikW
            UotgTu+diTgjAI1j2ecgPeziT2JFzqeGeC6owXnuVLKTzYbpI8cdvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u7wzh5ljlvz2kq7ha7pxpky2rw5llzgnhkaj0xq80httdpxvsagqz8pzll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T12:30:47Z"
    mac: ENC[AES256_GCM,data:qTwn9C4U7Q8EcVULKpQomsLCskTY+q+nbDXtMVe6idkEN4MvLGATrQTz2yhND+qvxd/CCgImS8Y4d2EwJw4GmluIdzlRM/x6zVpDIi4jaIC6STgVfHDV9oZqSSqgPm74f09YTzWa2d+AJ3HztZ8BRUQ4JxedgqHJ2In6+EyGKtE=,iv:tYuHgfMaKOtYIVd2RrUqzBDl4elnLwYgobXTkTe8s/k=,tag:Zz26QG6+sgdnb4TFIkP12g==,type:str]
    version: 3.13.1
