apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: umami-oauth2-proxy
    namespace: umami
spec:
    secretTemplates:
        - name: umami-oauth2-proxy
          stringData:
            OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:uyvDOoKWepOGXgaHB7YuY+gSyuuq2NgjSuzlG3e/8aXhtgYWxVTSTg==,iv:xoNxZGvTUCYd9smckm9q0U17nxiQDFRaemjiS0w4Hvs=,tag:YC1Zjr+ble9J6rZRJNaHHQ==,type:str]
            OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:Sadgbu2M0qeIopt8ZX4p2AvEXZMqpekzui2l9aiesA2phteizaSh5ELPkKXZ0Pt8p2xthmM0s0mC6KhcUFsU3bYoMa1HyefnAOmyoe3prZQY1ndvUqcnMQR2bLGdMvy/AbinK8F45vg1pk8d7jdx7yNT2rJoCElnO6VZRnqG0UY=,iv:cahwvNzkfY2TUZiRyAkHvqvj2g49TCN8bTu3Lzj43Bw=,tag:E/V7g2+8qkWTZ9btKTc3SA==,type:str]
            OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:Cnp16+FDXn3LEJbeWm9cZgf91tHyIZRqrJaNNa6exkrzdW1JVe3/kozdKtM=,iv:mtvzc4W2iVwtnjSiG2xe4W9d0fj8WkhrA5pCZQLXrn4=,tag:aQj68MgrrjNNXU4+n3RkJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZlovaGlTZ1RtMlFITmM5
            UnAxV0RIb2REZnAzU2R3aHJBWlp2NVJVZFRJCm8rSTRoaHoweXpYSHNxOUZmRHVh
            WkxrbWRlMFhUaVNzZkhpZGFMeWhidlEKLS0tIE4yRTJONGdTZXdCVTgzOXZtM0lw
            YjkxSjJxMzN4Y2xaMTYrREhEUy9JQVEKdxzBsdgP5POJH+e39VbI8epzFIMtF20H
            OtHN6xyTnd9YUbLGZTR9CUP2p/0ewiyhkX6RwYlaS9YjJR+I3FXgRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u7wzh5ljlvz2kq7ha7pxpky2rw5llzgnhkaj0xq80httdpxvsagqz8pzll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T16:55:03Z"
    mac: ENC[AES256_GCM,data:EAfgLrdwPbN+DuM2VRhHkHIetWtOY/moyyPFwBY3iHthmcU5L4p5ZnKFe/LABgFIhAWWUo+HNo2CEtDozOvbqFHEzKZ3sSv1EYhPyJ/G5kTWnq4RZ4mpHcXTugu+/R9S8oGkpq+kEvHzay02rP+Oh94ZqsX2MG0AglCAXUpYY1g=,iv:3BxF5RID3CAgyWg+bp5GatZPSXnyyNQMiD/I0pHLMg0=,tag:hiosf5CV72aKJeNIMvqb2w==,type:str]
    version: 3.13.1
