apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: umami-db
    namespace: umami
spec:
    secretTemplates:
        # CNPG role/initdb creds for the umami-pg cluster
        - name: umami-pg-user
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:fgk3oUM=,iv:PVdq2nSyNS2+xAOVz9pqtPGTuL1ZqHRfPfMaICzmfac=,tag:VuRBUpjDvqpbsUijINQ+nA==,type:str]
            password: ENC[AES256_GCM,data:eJnYT8JBWW+7A0Fc7OyUIm6ASCmJLb6oWDCNHHVYH90lXgiFsKZ/4tP9KzezXL8M,iv:QII8DBOkqOfBz8wzGi1qDLAymvzttlydrnoBUEo3wrM=,tag:towMDoRuN4Lbu8Wg+OzwgQ==,type:str]
        # umami app config
        - name: umami-secrets
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:Ovx7ado/rDYhyqtha1yc4GuJoKnz0a5Rc+vKRnQjRH+yaLEfxY75pvzb/IrkiyKgXIhNCGVz7iIXmeZfSOf9TXnfpDkOFq3tWThyA0pvF5cprsJpFscsF4uNjj6DkRKChUXd8tcBaykC9/q8iWL5Szqb,iv:ZxwJC8Fhnn6upxWDXiya617MqMCQTZOKtwEEvNvT9i4=,tag:XEHZ6RB4BhPHYsm1alpTdA==,type:str]
            APP_SECRET: ENC[AES256_GCM,data:6iaeIRpNUss57ODw95W5YsP7WIf3PD/LKFpvG8Mtz0IXiHmipfRNqcEfLSidv8q2CWW9gbfWQZWhfQ2V20ObFA==,iv:zZh1fBQ05l1oB5IgwYfiO9+C2+ka7M3eCSqV0k5LiQM=,tag:2riWJs6MLe7/OjTkoR87dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ak5MOG1EVkxMTmU0djUw
            NE50K0FFalRSSFloN3BJYVNzbEU5SXBVMUc0CkZmNFozWGhGUXVXVmE3U3pxNXNF
            SXJXU25GU1QxR0pmdW1aRjFjZU1Id2sKLS0tIE8rS3hVYWNZRWtLeWpKbTYybGZL
            OWFsdkZ4SlZ4UUFnUC9XTno1M05FbHMKnJ16iLj/4JL8JuQVj8vDS83qJUJs/4CV
            7UNex1uXKn8oXFsvRcdkdc4HdMl1LmKLM5MD292o88DsEB9CcJ7nMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u7wzh5ljlvz2kq7ha7pxpky2rw5llzgnhkaj0xq80httdpxvsagqz8pzll
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T16:40:51Z"
    mac: ENC[AES256_GCM,data:f6kEYOlhTOin8P584fJyJ10UI5vONTEL4ctBO1Ap4UUtPLNhl7Va8sCxkLsdGiGhPKTBl0ppVdfc8RE9Boh46Nxsy/4tsM5IUxmkjqysS3Gl5P//XXIjPkhrgQmbqDYpWz6yR7DZz0QKWpeDgay5shv+4y8dEC21qteA34Gmrlw=,iv:j1knczDnvLDcs8hTpnnI8NQiiL9pcCqnYEi1Qxqy/30=,tag:e5LATo9q6SJgRLOgqEPuHw==,type:str]
    version: 3.13.1
