#!/usr/bin/env bash
# Creates the in-cluster age private key the sops-secrets-operator uses to decrypt
# SopsSecret resources. This is the ONE bootstrap secret that replaces the old
# per-component secret scripts — the root of trust for all SOPS-encrypted secrets.
# NOT stored in git (the matching public recipient is, in .sops.yaml).
#
# The key is read from .secrets/sops-age.key (generated by `age-keygen`,
# git-ignored — BACK IT UP; losing it makes every *.sops.yaml unreadable).
#
# Creates, in namespace `sops-secrets-operator`:
#   - sops-age-key : keys.txt = the age private key (mounted as SOPS_AGE_KEY_FILE)
#
# Usage:  ./bootstrap/sops-age-secret.sh
set -euo pipefail

export KUBECONFIG="${KUBECONFIG:-/etc/rancher/k3s/k3s.yaml}"
KEY_FILE="${SOPS_AGE_KEY:-.secrets/sops-age.key}"

info() { echo "[sops-age-secret] $*"; }

[[ -f "$KEY_FILE" ]] || { echo "missing $KEY_FILE — run: age-keygen -o $KEY_FILE"; exit 1; }

kubectl create namespace sops-secrets-operator --dry-run=client -o yaml | kubectl apply -f -

kubectl create secret generic sops-age-key \
  -n sops-secrets-operator \
  --from-file=keys.txt="$KEY_FILE" \
  --dry-run=client -o yaml | kubectl apply -f -

info "age key installed as secret 'sops-age-key' in ns 'sops-secrets-operator'."
