apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: johanjoel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vercevo/gitops-cluster
    targetRevision: HEAD
    path: applications/johanjoel
    directory:
      include: "*.yaml"
      exclude: "application.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: johanjoel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
