apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: backstage-pg
  namespace: backstage
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  storage:
    size: 10Gi
  managed:
    roles:
      - name: backstage
        ensure: present
        createdb: true
        login: true
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: backstage-pg-user
  bootstrap:
    initdb:
      database: backstage
      owner: backstage
      secret:
        name: backstage-pg-user
