apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: "1.22.*"
      helm:
        valueFiles:
          - $values/platform/airflow/values.yaml
    - repoURL: https://github.com/vercevo/gitops-cluster
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/vercevo/gitops-cluster
      targetRevision: HEAD
      path: platform/airflow
      directory:
        include: "{postgres.yaml,httproute.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
