apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: airflow-pg
  namespace: airflow
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  storage:
    size: 10Gi
  managed:
    roles:
      - name: airflow
        ensure: present
        createdb: true
        login: true
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: airflow-pg-user
  bootstrap:
    initdb:
      database: airflow
      owner: airflow
      secret:
        name: airflow-pg-user
