global:
  domain: argocd.bergtobias.com

server:
  ingress:
    enabled: false
  extraArgs:
    - --insecure

configs:
  params:
    server.insecure: "true"

  cm:
    users.anonymous.enabled: "false"
    application.resourceTrackingMethod: annotation
    url: https://argocd.bergtobias.com
    oidc.config: |
      name: Authentik
      issuer: https://authentik.bergtobias.com/application/o/argocd/
      clientID: argocd
      clientSecret: $oidc.authentik.clientSecret
      requestedScopes:
        - openid
        - profile
        - email

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, akadmin, role:admin
