crds:
  enabled: true   # install / upgrade CRDs via Helm

replicaCount: 1

prometheus:
  enabled: true
  servicemonitor:
    enabled: true   # prometheus-operator (kube-prometheus-stack) is installed
