global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: secret-key
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: authentik-pg-rw
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__USER
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-pg-user
          key: password
    - name: AUTHENTIK_REDIS__HOST
      value: authentik-redis
    - name: AUTHENTIK_LOG_LEVEL
      value: info

postgresql:
  enabled: false

redis:
  enabled: false

server:
  ingress:
    enabled: false
